#!/bin/bash

killtree() {
    local _pid=$2
    local _sig=$1
    local killroot=$3
#    kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_sig} ${_child} yes
    done
    [ -n "$killroot" ] && kill ${_sig} ${_pid} 2>/dev/null
}

if [ $# -eq 0 -o $# -lt 2 -o $# -gt 3 ]; then
    echo "Usage: $(basename $0) <signal> <pid> [ <killroot> ]"
    exit 1
fi

killtree $@
