#!/bin/bash

killtree() {
    local _pid=$2
    local _sig=$1
    local dontkillfather=$3
#    kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_sig} ${_child}
    done
    [ -z "$dontkillfather" ] || kill ${_sig} ${_pid} 2>/dev/null
}

if [ $# -eq 0 -o $# -gt 2 ]; then
    echo "Usage: $(basename $0) <signal> <pid>"
    exit 1
fi

killtree $@
